### PR TITLE
improvements to build.sh

### PR DESCRIPTION
**Pull request by Un1q32**
mostly shellcheck fixes, changed the huge if else block to a case statement, only change in functionality is changing the lld check to also check for ld.lld and ld64.lld, since some toolchains only include one and clang doesn't care

### CODE REVIEW

**Comment by tpoechtrager** [comment]
There are lots of unneeded automated "improvement" changes. Please revert them. The lld part is fine.

**Comment by Un1q32** [comment]
I did all of it manually, what parts should be removed?

**Comment by Un1q32** [comment]
I reverted some bits that dont change functionality

**Comment by Un1q32** [comment]
reasons for every change in the file:

line 10 fixes a potential bug where if $0 contained spaces functionality would be different

line 13 removes an extra space that was probably left by mistake

line 14 is the lld change

line 29 is changed because there is never any reason to use double = in single brackets, since single = works the same and is more portable

lines 34-69 change the if else block to a case statement which is better for readability and speed

line 79 changes the echo -n to a printf and quotes the variable, bash echo is unreliable for printing variables and printf is more portable

line 88 quotes the INSTALLPREFIX variable, which fixes a potential bug if the INSTALLPREFIX were to contain spaces

**Comment by tpoechtrager** [comment]
Thanks.

I am not sure about the `printf` change though. `echo` is Bash builtin. How is `printf` more portable considering `echo` is a builtin function? I agree for non-Bash shells, but I am enforing Bash in the Shebang.

`command -v` is a good catch. However, `which` should also be replaced in `tools/tools.sh`.

Also distros having `ld.lld` but not `lld` is kinda weird. `ld.lld` is a symlink to `lld`. `lld` is the actual binary.

The `case "$TARGET" in` code block can be removed entirely. It's old testing code.

Care to make these changes?

**Comment by Un1q32** [comment]
> I am not sure about the `printf` change though. `echo` is Bash builtin. How is `printf` more portable considering `echo` is a builtin function? I agree for non-Bash shells, but I am enforing Bash in the Shebang.

if you have time [this video](https://youtu.be/lq98MM2ogBk?si=ZhY7LBDFlKLWysqh) explains why bash's echo command is bad for printing variables, better to use printf

> Also distros having `ld.lld` but not `lld` is kinda weird. `ld.lld` is a symlink to `lld`. `lld` is the actual binary.

I'm not sure how common it actually is, but I saw [this](https://github.com/mstorsjo/llvm-mingw) renames lld to ld.lld instead of linking, probably because creating symlinks on windows requires admin rights and the only workaround is to use a wrapper exe, I decided to include it to guard against Murphy's law

**Comment by Un1q32** [comment]
I replaced the `which` in tools/tools.sh, and also replaced the code used to determine what version of make to run with a version that doesn't require manually specifying what platforms need to run `gmake` instead of `make`

**Comment by tpoechtrager** [comment]
Thanks for the video. He makes some good points! 

I merged your changes but simplified the `make` check a bit.

**Pull request merged**
